
services:
  - type: web
    name: fx-history
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_pg:app --bind 0.0.0.0:$PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fx-db
          property: connectionString
      - key: ALPHA_VANTAGE_API_KEY
        sync: false

databases:
  - name: fx-db
    plan: free
